/** @type {import('next').NextConfig} */

const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'pub-a1dbb3c658b341fabe5015e209050298.r2.dev',
      },
      {
        protocol: 'https',
        hostname: 'yamada-tools.jp',
      },
    ],
  },
  experimental: {
    serverActions: {
      bodySizeLimit: '10mb'
    },
    nodeMiddleware: true,
  },
  async headers() {
    return [
      {
        source: '/fonts/:path*',
        headers: [
          { key: 'Cache-Control', value: 'public, max-age=31536000, immutable' },
        ],
      },
      {
        source: '/(pdf|image|convert|generator|document)/:path*',
        headers: [
          { key: 'Cache-Control', value: 'public, max-age=3600, s-maxage=86400' },
        ],
      },
      {
        source: '/(account|auth|admin)/:path*',
        headers: [
          { key: 'Cache-Control', value: 'private, no-cache, no-store' },
        ],
      },
    ]
  },
  async rewrites() {
    return [
      {
        source: '/api-backend/:path*',
        destination: 'http://localhost:8001/:path*',
      },
    ]
  },
  async redirects() {
    return [
      { source: '/legal', destination: '/terms', permanent: true },
      { source: '/legal/terms', destination: '/terms', permanent: true },
      { source: '/api/pdf/pdf-to-excel', destination: '/pdf/pdf-to-excel', permanent: true },
      { source: '/api/pdf/pdf-to-word', destination: '/pdf/pdf-to-word', permanent: true },
      { source: '/api/convert/furigana', destination: '/convert/furigana', permanent: true },
      { source: '/api/pdf/excel-to-pdf', destination: '/pdf/excel-to-pdf', permanent: true },
      { source: '/api/pdf/rotate', destination: '/pdf/rotate', permanent: true },
      { source: '/api/pdf/reorder', destination: '/pdf/reorder', permanent: true },
      { source: '/&', destination: '/', permanent: true },
      { source: '/$', destination: '/', permanent: true },
      { source: '/blog/image-resize-sns-perfect-size', destination: '/blog', permanent: true },
      { source: '/blog/kakutei-shinkoku-receipt-pdf-2025', destination: '/blog', permanent: true },
      { source: '/blog/pdf----149867', destination: '/blog', permanent: true },
      { source: '/nisa-simulator', destination: '/finance/nisa-simulator', permanent: true },
      { source: '/jutaku-loan', destination: '/finance/jutaku-loan', permanent: true },
      { source: '/fx-calculator', destination: '/finance/fx-calculator', permanent: true },
      { source: '/retirement-simulator', destination: '/finance/retirement-simulator', permanent: true },
      { source: '/tools/ideco-nisa-comparison', destination: '/finance/ideco-nisa-comparison', permanent: true },
      { source: '/tools/nisa-simulator', destination: '/finance/nisa-simulator', permanent: true },
      { source: '/ideco-nisa-comparison', destination: '/finance/ideco-nisa-comparison', permanent: true },
      { source: '/souzoku-touki/guide/gikaku-and-bassoku', destination: '/souzoku-touki/guide/gimuka-and-bassoku', permanent: true },
      { source: '/business/houjin-bangou-search', destination: '/business/houjin-bangou-lookup', permanent: true },
      { source: '/document/bank-format', destination: '/convert/bank-format', statusCode: 301 },
      { source: '/pdf-text-input', destination: '/pdf/text-input', statusCode: 301 },
      { source: '/pdf/fill', destination: '/pdf/text-input', statusCode: 301 },
      { source: '/image/to-pdf', destination: '/pdf/image-to-pdf', statusCode: 301 },
      { source: '/image/jpg-to-png', destination: '/image/format-convert', statusCode: 301 },
      { source: '/image/convert', destination: '/image/format-convert', statusCode: 301 },
      { source: '/convert/csv-to-excel', destination: '/', statusCode: 301 },
      { source: '/document/quote', destination: '/', statusCode: 301 },
      { source: '/business/houjin', destination: '/business/houjin-search', statusCode: 301 },
      { source: '/generator/shouhizei', destination: '/', statusCode: 301 },
      { source: '/generator/charcount', destination: '/', statusCode: 301 },
      { source: '/business/jinkenhi-shiyuki', destination: '/', statusCode: 301 },
      { source: '/generator/zangyou-tegata', destination: '/', statusCode: 301 },
      { source: '/education/scholarship-repayment', destination: '/', statusCode: 301 },
      { source: '/debt/debt-free-calculator', destination: '/', statusCode: 301 },
      { source: '/loan/mortgage-calculator', destination: '/', statusCode: 301 },
      { source: '/utility/hourly-to-annual', destination: '/', statusCode: 301 },
      { source: '/utility/discount-calculator', destination: '/', statusCode: 301 },
      { source: '/cdn-cgi/l/email-protection', destination: '/', statusCode: 301 },
      { source: '/business/corporate-number-lookup', destination: '/business/houjin-bangou-lookup', permanent: true },
      { source: '/career/shitsugyo-ritsu/hokkaido', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/aomori', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/iwate', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/miyagi', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/akita', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/yamagata', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/fukushima', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/ibaraki', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/tochigi', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/gunma', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/saitama', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/chiba', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/tokyo', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/kanagawa', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/niigata', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/toyama', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/ishikawa', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/fukui', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/yamanashi', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/nagano', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/gifu', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/shizuoka', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/aichi', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/mie', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/shiga', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/kyoto', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/osaka', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/hyogo', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/nara', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/wakayama', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/tottori', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/shimane', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/okayama', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/hiroshima', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/yamaguchi', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/tokushima', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/kagawa', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/ehime', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/kochi', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/fukuoka', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/saga', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/nagasaki', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/kumamoto', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/oita', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/miyazaki', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/kagoshima', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/career/shitsugyo-ritsu/okinawa', destination: '/career/shitsugyo-ritsu', statusCode: 301 },
      { source: '/use-cases', destination: '/', permanent: true },
      { source: '/image/convert', destination: '/image', permanent: true },
      { source: '/generator/charcount', destination: '/generator/text-counter', permanent: true },
      { source: '/generator/zangyou-tegata', destination: '/generator', permanent: true },
      { source: '/generator/password-gen', destination: '/generator/password', permanent: true },
      { source: '/finance/houjinka-setsuzei-calculator', destination: '/finance', permanent: true },
      { source: '/finance/retirement-simulator', destination: '/blog/rougo-shikin-simulation-2026', permanent: true },
      { source: '/savings/interest-calculator', destination: '/finance', permanent: true },
      { source: '/business/jinkenhi-shiyuki', destination: '/business', permanent: true },
      { source: '/document/quote', destination: '/document', permanent: true },
      { source: '/care/kaigo-hoshu-calc', destination: '/', permanent: true },
      { source: '/en/business', destination: '/en/business/company-search', permanent: true },
      { source: '/blog/zengin-format-kanzen-guide', destination: '/blog/zengin-format-complete-guide-2026', statusCode: 301 }
    ]
  }
}
export default nextConfig
