export interface Tool {
  id: string;
  nameJa: string;
  nameEn: string;
  description: string;
  icon: string;
  path: string;
  apiEndpoint: string;
  acceptedTypes: string;
  maxFiles: number;
  category: "pdf" | "document" | "convert" | "image" | "generator";
  available: boolean;
}

// ============================================
// Section 1: PDFツール (20 tools) ✅ DONE
// ============================================
export const pdfTools: Tool[] = [
  // Core Tools (必須ツール)
  {
    id: "merge",
    nameJa: "PDF結合",
    nameEn: "Merge PDF",
    description: "複数のPDFを1つに結合。順番入替も簡単、無料で登録不要",
    icon: "📄",
    path: "/pdf/merge",
    apiEndpoint: "/api/pdf/merge",
    acceptedTypes: ".pdf",
    maxFiles: 50,
    category: "pdf",
    available: true,
  },
  {
    id: "compress",
    nameJa: "PDF圧縮",
    nameEn: "Compress PDF",
    description: "PDFを最大80%軽量化。画質そのまま、メール添付に最適",
    icon: "📦",
    path: "/pdf/compress",
    apiEndpoint: "/api/pdf/compress",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  {
    id: "split",
    nameJa: "PDF分割",
    nameEn: "Split PDF",
    description: "PDFを複数ファイルに分割。ページ指定で必要な部分だけ抽出",
    icon: "✂️",
    path: "/pdf/split",
    apiEndpoint: "/api/pdf/split",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  {
    id: "rotate",
    nameJa: "PDF回転",
    nameEn: "Rotate PDF",
    description: "PDFページを90度・180度回転。スキャン向き修正に便利",
    icon: "🔄",
    path: "/pdf/rotate",
    apiEndpoint: "/api/pdf/rotate",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  {
    id: "delete-pages",
    nameJa: "ページ削除",
    nameEn: "Delete Pages",
    description: "PDFから不要なページを削除。プレビューで確認しながら操作",
    icon: "🗑️",
    path: "/pdf/delete-pages",
    apiEndpoint: "/api/pdf/delete-pages",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  // Conversion Tools (変換ツール)
  {
    id: "image-to-pdf",
    nameJa: "画像→PDF",
    nameEn: "Image to PDF",
    description: "JPG・PNG画像をPDFに一括変換。複数画像を1つのPDFに",
    icon: "🖼️",
    path: "/pdf/image-to-pdf",
    apiEndpoint: "/api/pdf/image-to-pdf",
    acceptedTypes: ".jpg,.jpeg,.png,.gif,.webp",
    maxFiles: 20,
    category: "pdf",
    available: true,
  },
  {
    id: "pdf-to-image",
    nameJa: "PDF→画像",
    nameEn: "PDF to Image",
    description: "PDFを高画質JPG・PNGに変換。各ページを個別画像で保存",
    icon: "🖼️",
    path: "/pdf/pdf-to-image",
    apiEndpoint: "/api/pdf/pdf-to-image",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  {
    id: "pdf-to-word",
    nameJa: "PDF→Word",
    nameEn: "PDF to Word",
    description: "PDFをWord(.docx)に変換。レイアウト維持で編集可能に",
    icon: "📝",
    path: "/pdf/pdf-to-word",
    apiEndpoint: "/api/pdf/pdf-to-word",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  {
    id: "word-to-pdf",
    nameJa: "Word→PDF",
    nameEn: "Word to PDF",
    description: "Word文書をPDFに変換。フォント埋込で文字化け防止",
    icon: "📄",
    path: "/pdf/word-to-pdf",
    apiEndpoint: "/api/pdf/word-to-pdf",
    acceptedTypes: ".doc,.docx",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  {
    id: "excel-to-pdf",
    nameJa: "Excel→PDF",
    nameEn: "Excel to PDF",
    description: "ExcelをPDFに変換。レイアウト崩れなし、印刷にも最適",
    icon: "📊",
    path: "/pdf/excel-to-pdf",
    apiEndpoint: "/api/pdf/excel-to-pdf",
    acceptedTypes: ".xls,.xlsx",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  {
    id: "pdf-to-excel",
    nameJa: "PDF→Excel",
    nameEn: "PDF to Excel",
    description: "PDFの表データをExcelに変換。データ抽出・編集が簡単",
    icon: "📊",
    path: "/pdf/pdf-to-excel",
    apiEndpoint: "/api/pdf/pdf-to-excel",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  {
    id: "ppt-to-pdf",
    nameJa: "PPT→PDF",
    nameEn: "PPT to PDF",
    description: "PowerPointをPDFに変換。プレゼン資料の共有に便利",
    icon: "📽️",
    path: "/pdf/ppt-to-pdf",
    apiEndpoint: "/api/pdf/ppt-to-pdf",
    acceptedTypes: ".ppt,.pptx",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  {
    id: "pdf-to-ppt",
    nameJa: "PDF→PPT",
    nameEn: "PDF to PPT",
    description: "PDFをPowerPointに変換。スライド編集が可能に",
    icon: "📽️",
    path: "/pdf/pdf-to-ppt",
    apiEndpoint: "/api/pdf/pdf-to-ppt",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  // Security Tools (セキュリティツール)
  {
    id: "protect",
    nameJa: "PDF保護",
    nameEn: "Protect PDF",
    description: "PDFにパスワードを設定。128bit AES暗号化で安全保護",
    icon: "🔒",
    path: "/pdf/protect",
    apiEndpoint: "/api/pdf/protect",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  {
    id: "unlock",
    nameJa: "PDF解除",
    nameEn: "Unlock PDF",
    description: "PDFのパスワード保護を解除。編集・印刷を可能に",
    icon: "🔓",
    path: "/pdf/unlock",
    apiEndpoint: "/api/pdf/unlock",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  // Editing Tools (編集ツール)
  {
    id: "page-numbers",
    nameJa: "ページ番号追加",
    nameEn: "Add Page Numbers",
    description: "PDFにページ番号を追加。位置・書式を自由にカスタマイズ",
    icon: "🔢",
    path: "/pdf/page-numbers",
    apiEndpoint: "/api/pdf/page-numbers",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  {
    id: "watermark",
    nameJa: "透かし追加",
    nameEn: "Add Watermark",
    description: "PDFに透かし・ロゴを追加。社外秘・コピー禁止などに",
    icon: "💧",
    path: "/pdf/watermark",
    apiEndpoint: "/api/pdf/watermark",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  {
    id: "reorder",
    nameJa: "ページ並べ替え",
    nameEn: "Reorder Pages",
    description: "PDFのページ順を自由に変更。ドラッグ&ドロップで簡単",
    icon: "↕️",
    path: "/pdf/reorder",
    apiEndpoint: "/api/pdf/reorder",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  {
    id: "sign",
    nameJa: "PDF署名",
    nameEn: "Sign PDF",
    description: "PDFに電子署名・手書きサインを追加。契約書にも対応",
    icon: "✍️",
    path: "/pdf/sign",
    apiEndpoint: "/api/pdf/sign",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
  // OCR Tool
  {
    id: "ocr",
    nameJa: "PDF OCR",
    nameEn: "OCR PDF",
    description: "スキャンPDFの文字を認識。検索・コピー可能なPDFに変換",
    icon: "👁️",
    path: "/pdf/ocr",
    apiEndpoint: "/api/pdf/ocr",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    category: "pdf",
    available: true,
  },
];

// ============================================
// Section 2: 書類作成 (10 tools)
// ============================================
export const documentTools: Tool[] = [
  {
    id: "invoice",
    nameJa: "請求書作成",
    nameEn: "Invoice Generator",
    description: "インボイス制度対応の請求書を無料作成。PDF出力・保存可能",
    icon: "📑",
    path: "/document/invoice",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "document",
    available: true,
  },
  {
    id: "quotation",
    nameJa: "見積書作成",
    nameEn: "Quotation Generator",
    description: "プロ品質の見積書を無料作成。消費税自動計算・PDF出力",
    icon: "📋",
    path: "/document/quotation",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "document",
    available: true,
  },
  {
    id: "resume",
    nameJa: "履歴書作成",
    nameEn: "Resume Creator",
    description: "JIS規格の履歴書を作成。写真貼付・PDF出力対応",
    icon: "📝",
    path: "/document/resume",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "document",
    available: true,
  },
  {
    id: "cover-letter",
    nameJa: "送付状作成",
    nameEn: "Cover Letter Generator",
    description: "ビジネス送付状を簡単作成。FAX・郵送どちらにも対応",
    icon: "📨",
    path: "/document/cover-letter",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "document",
    available: true,
  },
  {
    id: "business-email",
    nameJa: "ビジネスメール作成",
    nameEn: "Business Email Generator",
    description: "正しい敬語のビジネスメールを生成。お詫び・依頼・お礼など",
    icon: "✉️",
    path: "/document/business-email",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "document",
    available: true,
  },
  {
    id: "business-card",
    nameJa: "名刺作成",
    nameEn: "Business Card Creator",
    description: "名刺をオンラインでデザイン。印刷用PDF出力・QR対応",
    icon: "💳",
    path: "/document/business-card",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "document",
    available: true,
  },
  {
    id: "vertical-text",
    nameJa: "縦書き文書作成",
    nameEn: "Vertical Text Document",
    description: "縦書き文書を作成・PDF出力。挨拶状・式辞・祝辞に",
    icon: "📜",
    path: "/document/vertical-text",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "document",
    available: true,
  },
  {
    id: "receipt",
    nameJa: "領収書作成",
    nameEn: "Receipt Generator",
    description: "領収書を無料作成。印紙税案内付き・PDF出力対応",
    icon: "🧾",
    path: "/document/receipt",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "document",
    available: true,
  },
  {
    id: "delivery-slip",
    nameJa: "納品書作成",
    nameEn: "Delivery Slip Generator",
    description: "納品書を簡単作成。請求書・見積書と連携可能",
    icon: "📦",
    path: "/document/delivery-slip",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "document",
    available: true,
  },
  {
    id: "fax-cover",
    nameJa: "FAX送付状作成",
    nameEn: "FAX Cover Sheet Generator",
    description: "FAX送付状を無料作成。枚数・件名を入力するだけ",
    icon: "📠",
    path: "/document/fax-cover",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "document",
    available: true,
  },
];

// ============================================
// Section 3: 変換ツール (10 tools)
// ============================================
export const convertTools: Tool[] = [
  {
    id: "zenkaku-hankaku",
    nameJa: "全角・半角変換",
    nameEn: "Zenkaku/Hankaku Converter",
    description: "全角↔半角を一括変換。電話番号・住所データ整形に最適",
    icon: "🔄",
    path: "/convert/zenkaku-hankaku",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "convert",
    available: true,
  },
  {
    id: "wareki-seireki",
    nameJa: "和暦・西暦変換",
    nameEn: "Japanese Era Converter",
    description: "和暦↔西暦を瞬時に変換。令和・平成・昭和に対応",
    icon: "📅",
    path: "/convert/date-converter",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "convert",
    available: true,
  },
  {
    id: "postcode",
    nameJa: "郵便番号検索",
    nameEn: "Postcode Lookup",
    description: "郵便番号から住所を検索。住所から郵便番号も逆引き可能",
    icon: "〒",
    path: "/convert/postcode",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "convert",
    available: true,
  },
  {
    id: "furigana",
    nameJa: "ふりがな変換",
    nameEn: "Furigana Converter",
    description: "漢字にふりがなを自動付与。ひらがな・カタカナ・ローマ字対応",
    icon: "あ",
    path: "/convert/furigana",
    apiEndpoint: "/api/convert/furigana",
    acceptedTypes: "",
    maxFiles: 0,
    category: "convert",
    available: true,
  },
  {
    id: "base64",
    nameJa: "Base64変換",
    nameEn: "Base64 Encoder/Decoder",
    description: "テキスト・画像をBase64にエンコード・デコード変換",
    icon: "🔐",
    path: "/convert/base64",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "convert",
    available: true,
  },
  {
    id: "url-encode",
    nameJa: "URLエンコード",
    nameEn: "URL Encoder/Decoder",
    description: "日本語URLをエンコード・デコード。文字化け解決に",
    icon: "🔗",
    path: "/convert/url-encode",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "convert",
    available: true,
  },
  {
    id: "phone-formatter",
    nameJa: "電話番号整形",
    nameEn: "Phone Number Formatter",
    description: "電話番号をハイフン付きに整形。携帯・固定・フリーダイヤル対応",
    icon: "📞",
    path: "/convert/phone-formatter",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "convert",
    available: true,
  },
  {
    id: "excel-a4-fit",
    nameJa: "A4ぴったりExcel変換",
    nameEn: "Excel A4 Fit Converter",
    description: "ExcelをA4サイズぴったりにPDF変換。印刷ズレを防止",
    icon: "📐",
    path: "/convert/excel-a4-fit",
    apiEndpoint: "/api/convert/excel-a4-fit",
    acceptedTypes: ".xls,.xlsx",
    maxFiles: 1,
    category: "convert",
    available: false,
  },
  {
    id: "bank-format",
    nameJa: "全銀フォーマット変換",
    nameEn: "Zengin Format Converter",
    description: "銀行振込データを全銀形式に変換。全銀フォーマットの作り方も解説",
    icon: "🏦",
    path: "/convert/bank-format",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "convert",
    available: true,
  },
  {
    id: "unit-converter",
    nameJa: "単位変換",
    nameEn: "Unit Converter",
    description: "長さ・重さ・面積・温度など50種以上の単位を相互変換",
    icon: "📐",
    path: "/convert/unit",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "convert",
    available: true,
  },
];

// ============================================
// Section 4: 画像ツール (8 tools)
// ============================================
export const imageTools: Tool[] = [
  {
    id: "id-photo",
    nameJa: "証明写真作成",
    nameEn: "ID Photo Maker",
    description: "マイナンバー・パスポート・履歴書用の証明写真を作成",
    icon: "🪪",
    path: "/image/id-photo",
    apiEndpoint: "/api/image/id-photo",
    acceptedTypes: ".jpg,.jpeg,.png",
    maxFiles: 1,
    category: "image",
    available: false,
  },
  {
    id: "compress-image",
    nameJa: "画像圧縮",
    nameEn: "Image Compressor",
    description: "画像を最大80%軽量化。画質そのまま、一括20枚まで処理可能",
    icon: "📦",
    path: "/image/compress",
    apiEndpoint: "",
    acceptedTypes: ".jpg,.jpeg,.png,.webp",
    maxFiles: 20,
    category: "image",
    available: true,
  },
  {
    id: "resize-image",
    nameJa: "画像リサイズ",
    nameEn: "Image Resizer",
    description: "画像サイズを自由に変更。SNS・Web用に最適化",
    icon: "🖼️",
    path: "/image/resize",
    apiEndpoint: "",
    acceptedTypes: ".jpg,.jpeg,.png,.webp,.gif",
    maxFiles: 1,
    category: "image",
    available: true,
  },
  {
    id: "convert-image",
    nameJa: "画像形式変換",
    nameEn: "Image Format Converter",
    description: "JPG・PNG・WebP・GIFを相互変換。一括変換対応",
    icon: "🔄",
    path: "/image/format-convert",
    apiEndpoint: "",
    acceptedTypes: ".jpg,.jpeg,.png,.webp,.gif,.bmp",
    maxFiles: 20,
    category: "image",
    available: true,
  },
  {
    id: "rotate-image",
    nameJa: "画像回転",
    nameEn: "Image Rotate",
    description: "画像を90度・180度・270度回転。一括処理対応",
    icon: "🔄",
    path: "/image/rotate",
    apiEndpoint: "",
    acceptedTypes: ".jpg,.jpeg,.png,.webp,.gif,.bmp",
    maxFiles: 20,
    category: "image",
    available: true,
  },
  {
    id: "remove-bg",
    nameJa: "背景削除",
    nameEn: "Background Remover",
    description: "画像の背景をAIで自動削除。透過PNG出力対応",
    icon: "✂️",
    path: "/image/remove-bg",
    apiEndpoint: "/api/image/remove-bg",
    acceptedTypes: ".jpg,.jpeg,.png",
    maxFiles: 1,
    category: "image",
    available: false,
  },
  {
    id: "crop-image",
    nameJa: "画像切り抜き",
    nameEn: "Image Cropper",
    description: "画像を任意のサイズに切り抜き。SNSアイコン作成にも",
    icon: "✂️",
    path: "/image/crop",
    apiEndpoint: "",
    acceptedTypes: ".jpg,.jpeg,.png,.webp",
    maxFiles: 1,
    category: "image",
    available: true,
  },
  {
    id: "qr-code",
    nameJa: "QRコード作成",
    nameEn: "QR Code Generator",
    description: "URL・テキスト・WiFi用QRコードを無料作成。高解像度PNG出力",
    icon: "📱",
    path: "/image/qr-code",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "image",
    available: true,
  },
];

// ============================================
// Section 5: 計算・生成ツール (20 tools)
// ============================================
export const generatorTools: Tool[] = [
  {
    id: "password-generator",
    nameJa: "パスワード生成",
    nameEn: "Password Generator",
    description: "安全な強力パスワードを瞬時に生成。長さ・文字種を指定可能",
    icon: "🔐",
    path: "/generator/password",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "password-zip",
    nameJa: "パスワード付きZIP",
    nameEn: "Password ZIP Creator",
    description: "パスワード付きZIPファイルを作成。複数ファイルを暗号化圧縮",
    icon: "🗜️",
    path: "/generator/password-zip",
    apiEndpoint: "",
    acceptedTypes: "*",
    maxFiles: 10,
    category: "generator",
    available: true,
  },
  {
    id: "char-counter",
    nameJa: "文字数カウント",
    nameEn: "Character Counter",
    description: "文字数・単語数・行数をリアルタイムでカウント。SNS投稿に便利",
    icon: "📝",
    path: "/generator/character-count",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "tax-calculator",
    nameJa: "消費税計算",
    nameEn: "Tax Calculator",
    description: "8%・10%の税込・税抜価格を瞬時に計算。逆算も対応",
    icon: "🧮",
    path: "/generator/tax-calculator",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "random-picker",
    nameJa: "ランダム抽選",
    nameEn: "Random Picker",
    description: "名前・アイテムをランダム抽選。公平な当選者選びに",
    icon: "🎲",
    path: "/generator/random-picker",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "text-diff",
    nameJa: "テキスト差分比較",
    nameEn: "Text Diff",
    description: "2つのテキストの差分を色分け表示。変更箇所が一目瞭然",
    icon: "📝",
    path: "/generator/text-diff",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "hash-generator",
    nameJa: "ハッシュ生成",
    nameEn: "Hash Generator",
    description: "MD5・SHA-256などのハッシュ値を計算。ファイル整合性確認に",
    icon: "#️⃣",
    path: "/generator/hash",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "holiday-checker",
    nameJa: "祝日確認",
    nameEn: "Holiday Checker",
    description: "日本の祝日・振替休日を確認。年間カレンダー表示対応",
    icon: "📅",
    path: "/generator/holiday-checker",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "hanko",
    nameJa: "電子印鑑作成",
    nameEn: "Digital Hanko Generator",
    description: "デジタル印鑑を無料作成。透過PNG出力、在宅ワークに必須",
    icon: "🔴",
    path: "/generator/hanko",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "age-calc",
    nameJa: "年齢計算",
    nameEn: "Age Calculator",
    description: "生年月日から年齢・干支・星座を計算。和暦入力にも対応",
    icon: "🎂",
    path: "/generator/age-calc",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "color-convert",
    nameJa: "カラーコード変換",
    nameEn: "Color Converter",
    description: "HEX・RGB・HSLを相互変換。カラーピッカー付き",
    icon: "🎨",
    path: "/generator/color-convert",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "lorem-ipsum",
    nameJa: "ダミーテキスト生成",
    nameEn: "Lorem Ipsum Generator",
    description: "Lorem Ipsum・日本語ダミー文章を生成。デザイン確認用に",
    icon: "📝",
    path: "/generator/lorem-ipsum",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "json-format",
    nameJa: "JSON整形",
    nameEn: "JSON Formatter",
    description: "JSONを見やすく整形・圧縮。バリデーション機能付き",
    icon: "{ }",
    path: "/generator/json-format",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "regex-test",
    nameJa: "正規表現テスター",
    nameEn: "Regex Tester",
    description: "正規表現パターンをリアルタイムでテスト。マッチ結果をハイライト",
    icon: ".*",
    path: "/generator/regex-test",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "qr-reader",
    nameJa: "QRコード読み取り",
    nameEn: "QR Code Reader",
    description: "画像からQRコードを読み取り。カメラ・ファイル両対応",
    icon: "📷",
    path: "/generator/qr-reader",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "text-case",
    nameJa: "大文字・小文字変換",
    nameEn: "Text Case Converter",
    description: "大文字・小文字・タイトルケースに一括変換。プログラマー向け",
    icon: "Aa",
    path: "/generator/text-case",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "invoice-validator",
    nameJa: "インボイス番号検証",
    nameEn: "Invoice Number Validator",
    description: "適格請求書発行事業者のT番号を国税庁DBで検証",
    icon: "✅",
    path: "/generator/t-number",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "nenmatsu-calc",
    nameJa: "年末調整計算",
    nameEn: "Year-End Tax Calculator",
    description: "年末調整の還付金・追加徴収をシミュレーション。控除額も自動計算",
    icon: "💴",
    path: "/generator/nenmatsu-calc",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "envelope-print",
    nameJa: "封筒印刷・宛名印刷",
    nameEn: "Envelope Address Printer",
    description: "日本の全封筒サイズ対応の宛名印刷。縦書き・横書き選択可能",
    icon: "✉️",
    path: "/generator/envelope-print",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
  {
    id: "salary-calc",
    nameJa: "給与手取り計算",
    nameEn: "Net Salary Calculator",
    description: "額面から手取り額を計算。社会保険・所得税・住民税を自動算出",
    icon: "💰",
    path: "/generator/salary-calc",
    apiEndpoint: "",
    acceptedTypes: "",
    maxFiles: 0,
    category: "generator",
    available: true,
  },
];

// ============================================
// All tools combined
// ============================================
export const allTools: Tool[] = [
  ...pdfTools,
  ...documentTools,
  ...convertTools,
  ...imageTools,
  ...generatorTools,
];

// ============================================
// Helper functions
// ============================================
export const getToolById = (id: string): Tool | undefined => {
  return allTools.find(t => t.id === id);
};

export const getToolsByCategory = (category: Tool["category"]): Tool[] => {
  switch (category) {
    case "pdf":
      return pdfTools;
    case "document":
      return documentTools;
    case "convert":
      return convertTools;
    case "image":
      return imageTools;
    case "generator":
      return generatorTools;
    default:
      return [];
  }
};

export const getAvailableTools = (): Tool[] => {
  return allTools.filter(t => t.available);
};

export const getToolCount = () => ({
  pdf: pdfTools.length,
  document: documentTools.length,
  convert: convertTools.length,
  image: imageTools.length,
  generator: generatorTools.length,
  total: allTools.length,
});

// For backward compatibility
export const officeTools = documentTools;
